[main]
font=JetBrainsMono Nerd Font:size=16
fields=name,generic,comment,exec
terminal=foot # Ou ton terminal habituel
prompt="❯ " 
layer=top

# Dimensions du menu
width=30
tabs=4
horizontal-pad=20
vertical-pad=15
inner-pad=10

# Arrondi des angles pour matcher avec Waybar (border-radius: 10px)
border-radius=10

[colors]
# Format : RRGGBBAA (AALes deux derniers chiffres gèrent la transparence)
# background: Même couleur sombre très translucide que ta Waybar
background=0a0a0f66

# text: Blanc brillant
text=ffffffff

# prompt: Blanc brillant
prompt=ffffffff

# input: Blanc pour le texte tapé
input=ffffffff

# selection: Le fond de l'élément survolé/sélectionné (léger reflet blanc)
selection=ffffff14

# selection-text: Texte sélectionné en blanc
selection-text=ffffffff

# border: La bordure fine et claire pour l'effet "tranchant" du verre
border=ffffff1a

[border]
width=1
radius=10
